#pragma once

#include "./clear_effects.h"

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define NO_ACTION_ONESHOT
#define LAYER_STATE_8BIT

#define HOLD_ON_OTHER_KEY_PRESS
// #define TAP_CODE_DELAY 10

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define UNICODE_KEY_WINC KC_RGUI
#ifdef OS_DETECTION_ENABLE
#    define UNICODE_CYCLE_PERSIST false
#endif // OS_DETECTION_ENABLE

#define LEADER_PER_KEY_TIMING
#define LEADER_NO_TIMEOUT


#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP

#define RGB_MATRIX_DISABLE_KEYCODES
#define RGB_MATRIX_DEFAULT_VAL 100
#ifdef RGB_MATRIX_CUSTOM_USER
#    define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CUSTOM_RGB_LAYERS
#else // RGB_MATRIX_CUSTOM_USER
#    define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TYPING_HEATMAP
#endif // RGB_MATRIX_CUSTOM_USER
