CAPS_WORD_ENABLE = yes
CONSOLE_ENABLE = yes
GRAVE_ESC_ENABLE = no
LEADER_ENABLE = yes
LTO_ENABLE = yes
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
NKRO_ENABLE = no
RGB_MATRIX_CUSTOM_USER = no
RGB_MATRIX_ENABLE = yes
RING_BUFFERED_6KRO_REPORT_ENABLE = yes
UNICODEMAP_ENABLE = yes
OS_DETECTION_ENABLE = yes
DIP_SWITCH_ENABLE = yes

SRC += atte.c
